name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python - <<'PY'
          import os
          os.environ.setdefault("MPLBACKEND", "Agg")
          print("MPLBACKEND set to", os.environ["MPLBACKEND"])
          PY

      - name: Pre-run sanity check
        run: |
          python --version
          pip list
          echo "Repo tree:"
          ls -la
          echo "Search for expected inputs:"
          ls -la sample* || true
          ls -la data || true

      - name: Run pipeline (verbose)
        env:
          MPLBACKEND: Agg
          PYTHONUNBUFFERED: "1"
        run: |
          set -e
          echo "Running Datagen.py..."
          python Datagen.py
          echo "Datagen.py completed."

      - name: Show outputs (if any)
        run: |
          echo "Listing outputs if present:"
          ls -la metrics.json || true
          ls -la worst_anomalies.csv || true
          ls -la artifacts || true

      - name: Upload artifacts (don’t fail if missing)
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: |
            metrics.json
            worst_anomalies.csv
            artifacts/**
          if-no-files-found: warn
